theme: jekyll-theme-cayman
title: Finite Difference Method
description: Application to One-dimensional Consolidation
highlighter: rouge
kramdown:
    math_engine: mathjax
    syntax_highlighter: rouge
